variable "security_group" {}
variable "DB_Username" {}
variable "DB_Password" {}
variable "snapshot_identifier" {}
variable "rdsdbname" {}
variable "parameter_group_name" {}
variable "skip_final_snapshot" {}
variable "instance_class" {}
variable "required_tags" {}
variable "subnet_ids" {}